[package]
name = "esp_remote_common"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = "1.3.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

